version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  versioning-strategy: increase
  labels:
  - dependencies
  - maintenance
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: weekly
  reviewers:
  labels:
  - dependencies
  - maintenance
